You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2ad884e12dd8>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido',)': /simple/numpy/
Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2ad884577e80>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido',)': /simple/numpy/
Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2ad884577908>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido',)': /simple/numpy/
Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2ad884577c88>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido',)': /simple/numpy/
Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2ad884577a20>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido',)': /simple/numpy/
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "test/test_tfg_ker.py", line 13, in <module>
    from utils import datasets as ds
  File "/home/jlsuarez/pyDML/utils/__init__.py", line 4, in <module>
    from .kfold_tester import kfold_tester_supervised_knn
  File "/home/jlsuarez/pyDML/utils/kfold_tester.py", line 16, in <module>
    from dml import(
  File "/home/jlsuarez/pyDML/dml/__init__.py", line 6, in <module>
    from .pca import PCA
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "test/test_tfg_ker.py", line 13, in <module>
    from utils import datasets as ds
  File "/home/jlsuarez/pyDML/utils/__init__.py", line 4, in <module>
    from .kfold_tester import kfold_tester_supervised_knn
  File "/home/jlsuarez/pyDML/utils/kfold_tester.py", line 16, in <module>
    from dml import(
  File "/home/jlsuarez/pyDML/dml/__init__.py", line 8, in <module>
    from .lsi import LSI
ImportError: /home/jlsuarez/pyDML/dml/lsi.cpython-36m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/jlsuarez/.local/lib/python3.6/site-packages/numpy/core/numeric.py:492: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:433: ComplexWarning: Casting complex values to real discards the imaginary part
  array = np.array(array, dtype=dtype, order=order, copy=copy)
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/jlsuarez/.local/lib/python3.6/site-packages/numpy/core/numeric.py:492: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)
/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:433: ComplexWarning: Casting complex values to real discards the imaginary part
  array = np.array(array, dtype=dtype, order=order, copy=copy)
test/test_tfg_ker.py:196: RuntimeWarning: overflow encountered in double_scalars
  dml.fit(xtr,ytr)
/usr/local/lib/python3.6/site-packages/sklearn/metrics/pairwise.py:247: RuntimeWarning: overflow encountered in multiply
  distances *= -2
/usr/local/lib/python3.6/site-packages/sklearn/metrics/pairwise.py:248: RuntimeWarning: invalid value encountered in add
  distances += XX
/usr/local/lib/python3.6/site-packages/sklearn/metrics/pairwise.py:248: RuntimeWarning: overflow encountered in add
  distances += XX
/usr/local/lib/python3.6/site-packages/sklearn/metrics/pairwise.py:249: RuntimeWarning: invalid value encountered in add
  distances += YY
/usr/local/lib/python3.6/site-packages/sklearn/metrics/pairwise.py:249: RuntimeWarning: overflow encountered in add
  distances += YY
test/test_tfg_ker.py:196: RuntimeWarning: invalid value encountered in double_scalars
  dml.fit(xtr,ytr)
